on:
  push:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
        
    strategy:
      fail-fast: false
      matrix:
        size: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152]

    env:
      VERSION: 1.0.0-g${{ github.sha }}-${{ matrix.size }}

    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - run: |
          cat > test2.csproj << EOM
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>netstandard2.0</TargetFramework>
            </PropertyGroup>
            <ItemGroup>
              <EmbeddedResource Include="embedded.txt" />
            </ItemGroup>
          </Project>
          EOM

      - run: dd if=/dev/random of=embedded.txt count=${{ matrix.size }} bs=1024

      - run: dotnet pack -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} -p:Version=${{ env.VERSION }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - run: ls -l bin/Debug/*.nupkg

      - run: dotnet nuget push bin/Debug/*.nupkg
        env:
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLE: false

